### ISSUE TITLE
Client.Get returns errors.IsNotFound when accessing a resource from "distant" cluster

### ISSUE THREAD

**Issue by cscetbon** [admiraltyio/multicluster-service-account#16]
Hi,

I'm using kubemcsa to create a secret that is used by multi-casskop operator to interact with multiple kubernetes clusters. (You talked to Sebastien in the past). The issue in my local setup is that every time  it does a Get it gets a NotFound error which is confusing https://github.com/Orange-OpenSource/casskop/blob/rolling-restart/multi-casskop/pkg/controller/multi-casskop/cmc_utils.go#L31. However, it can create objects without any problem and no permission error is returned during a Get as it is a NotFound error https://github.com/Orange-OpenSource/casskop/blob/rolling-restart/multi-casskop/pkg/controller/multi-casskop/cmc_utils.go#L82. So in short, our code tries to get the resource but gets a NotFound error, then attempts to create the object and then gets an [alreadyExists](https://github.com/Orange-OpenSource/casskop/blob/rolling-restart/multi-casskop/pkg/controller/multi-casskop/cmc_utils.go#L83) error 🤷‍♂️  Any idea what's going on ?

I'm using the same cluster for the local and remote, just using different namespaces to be sure objects with same names do not conflict. Here is the cluster role I use to be able to access resources in the distance context which is simply another namespace like I said:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inter-ns
rules:
- apiGroups:
  - db.orange.com
  resources:
  - cassandraclusters
  verbs:
  - "*"
- apiGroups:
    - db.orange.com
  resources:
    - cassandraclusters/status
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inter-ns-cl1
  namespace: cluster2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inter-ns
subjects:
- kind: ServiceAccount
  name: cassandra-operator
  namespace: cluster1
```
